### ISSUE TITLE
Error in transferring data from forms to obsinitial 

### ISSUE THREAD

**Issue by Iyakaremyevedaste** [opencdms/Climsoft#420] opened 2018-11-13 06:34 UTC
![capture](https://user-images.githubusercontent.com/44503727/48395081-a8184c80-e71e-11e8-92f8-bbfa4e65bc9c.JPG)
I am encountering such an error message when I upload data from forms to observationinitial

**Comment by Patowhiz** [comment] 2018-11-13 07:03
What was the year and month selected? It's covered by the progress.

**Comment by Iyakaremyevedaste** [comment] 2018-11-13 07:44
I selected many years. In forms we had data recorded in the 1960s and the current year 2018

**Comment by mhabimana** [comment] 2018-11-13 12:03
@Iyakaremyevedaste : I found that in your data (form daily2) there are data which does not have corresponding elements in Climsoft e.g: 516,517,518,520,etc. Please can you check and confirm this?

**Comment by smachua** [comment] 2018-11-13 17:54
@Patowhiz and @Iyakaremyevedaste note that while uploading from forms all data is transferred from key entry table to observationinitial. There is no selection to be done. The error here is about invalid date.  
Please @Patowhiz find out whether the uploading process is creating an invalid date or the key entry is allowing saving of records with invalid date e.g. 31/09/2017.
Meanwhile try to round the % in the uploading progress to whole numbers.
Also the time taken to complete the uploading process is also unnecessarily long.

**Comment by Iyakaremyevedaste** [comment] 2018-11-15 07:36
@mhabimana by checking in obselement table, I found those elements are there. However, those elements cannot be transferred from excel sheet to obsinitial!!

**Comment by mhabimana** [comment] 2018-11-15 07:43
@Iyakaremyevedaste Thanks,Kindly share with me your script for obselement table for further investigation.

**Comment by Iyakaremyevedaste** [comment] 2018-11-15 08:22
@mhabimana script for obselement was shared in your email. Thanks

**Comment by Patowhiz** [comment] 2018-11-19 14:35
Upon investigating this issue further, this is what we found out. The following records have values in day 31 for month 6. This leads to incorrect date, which makes leads to the error shown.

The records with;
Station 10306100,  Element 5 in 1955, month 6 has value in day 31 and month 7 is missing.
Station 10306100, Element 17 in 1954, month 6 has value in day 31.
Station 10306100  Element 96  in 1967 month 6 has value in day 31.

**Comment by mhabimana** [comment] 2018-11-19 15:01
@Patrick: Thanks for this observation,what about having flag=M in the flags data cells which are supposed to be deactivated by the system?
Station 10101100, Element 2 ,in 2017, month 9, flag 31=M, 
Station 10306100, Element 2 in 1955,1957,1959, month 9 ,flag 31=M
Can this prevent data to be uploaded as well into observationinitial?

**Comment by mhabimana** [comment] 2018-11-19 15:05
@Patowhiz Have you looked at uploading the hourly data into observationinitial as well?

**Comment by mhabimana** [comment] 2018-11-19 15:07
@Iyakaremyevedaste : Can you re-check again and correct your data in the form_daily2 ?

**Comment by Patowhiz** [comment] 2018-11-19 15:11
Flag won't prevent the data from being uploaded. The specific record will just be ignored

**Comment by mhabimana** [comment] 2018-11-19 15:12
@Patowhiz :Noted

**Comment by Patowhiz** [comment] 2018-11-19 15:12
@mhabimana apart from the speed, hourly data works fine from my end.

**Comment by smachua** [comment] 2018-11-19 17:06
@Patowhiz we need to brainstorm on how data for those invalid dates is occurring. Meanwhile I would suggest that the uploading process should skip such records and upload the rest to the end to avoid frustrating the users. Records with invalid dates may be flagged for investigation.

**Comment by Patowhiz** [comment] 2018-11-20 06:56
@smachua that's true. We'll work on making the upload better and that flexible.

**Comment by mhabimana** [comment] 2018-11-20 07:04
@Iyakaremyevedaste After removing the suspected values pointed by @Patowhiz I managed to load these data on my side though I had to wait for few minutes.

**Comment by amosuwizeye** [comment] 2018-11-20 09:15
Thanks for the support

**Comment by mhabimana** [comment] 2018-11-20 09:16
@amosuwizeye :Thanks

**Comment by mhabimana** [comment] 2018-11-21 13:47
@Patowhiz Just to find out your progress on this. One of the annoying thing on the form upload progress bar  below it that in case of uploading many records (e.g. 28395),it shows that the upload has completed and yet it is still going on in the background (see below):
![image](https://user-images.githubusercontent.com/10340170/48844881-25416280-edac-11e8-9471-5e8ac4ee998b.png)
Below are the required improvement on the progress bar: 
- Improve the speed of upload;
- The progress bar should show the total number of records being uploaded in respect to the total number of records available to upload and not the progress in percentage (e.g.(1200 of 23000);
- The waiting mouse also will be good to show that the upload operation is in progress;
- Display a message when completed(e.g.Records have been uploaded successfully)

**Comment by Iyakaremyevedaste** [comment] 2018-11-21 14:39
Dear all, there is another issue to solve on QC. When you have say for example data from Jan to October 2018 in obsinitial and it happens previously you did QC for Jan data only. When you want to perform Qc on the remaining months and in your query you select from Jan to Dec. Qc command will be executed but Qc status will not change i.e data cannot be loaded to the obsfinal.

**Comment by mhabimana** [comment] 2018-11-21 14:52
@Iyakaremyevedaste Thanks for this, Can you please comment on another issue related to QC or create a new issue on this? This issue is meant for upload from data forms to observationinitial only.

**Comment by smachua** [comment] 2018-11-30 09:34
It seems this bug may take longer to get fixed.  Almost all users (e.g. Rwanda and Seychelles) are experiencing the problem since they started using the new forms. In particular Seychelles has not been able to push data to observationinitial since upgrading from V4.0.  Hence some important climate products are pending. The issue is only with 'form_daily2'.
 
I am aware that efforts are being made to resolve the issue. But in order to help the affected users upload their data am going to revert to the upload code used in the old forms since it was working ok.  This commit will also include a fix to the QC issue raised by @Iyakaremyevedaste .

**Comment by volloholic** [comment] 2018-11-30 10:32
@smachua I am confused with the problem the Seychelles is facing can you give more details.

As I understand from my investigation with Patrick, in Rwanda the problem was that there were invalid dates which had been imported to the form_daily2 table. We checked that in the current implementation it did not appear to be possible to enter such dates from the form so these must have been imported to the database. We ran through and identified the problem dates for Rwanda and I believe this solved the problem. We could also identify invalid dates in the Seychelles data if they have the same problem with data they have imported.

@Patowhiz is working on the improvements suggested by @mhabimana but these are purely cosmetic and will not fix any issues for the Seychelles. 

There are a few different possible approaches to resolve this issue permanently we will discuss the with the AMI team and @maxwellfundi will create an issue to take forward the discussion. Meanwhile if the Seychelles issue can be shared we will ensure that we can fix it.

**Comment by smachua** [comment] 2018-11-30 13:04
@volloholic am not sure where the confusion is because the issues raised on data upload from the new form_daily2 have not been resolved yet. The are:
(i) The process stopping with error message 'un-representable Date Time,
(ii) The process takes unnecessarily long to complete,
(iii) The progress % not rounded to whole numbers but many decimal points.
![image](https://user-images.githubusercontent.com/12034121/49290854-43e4df00-f4b9-11e8-9927-135e1fcb03b9.png)

While (ii) and (iii) can be tolerated (i) brings everything to a stop. I had suggested to @Patowhiz that the upload code be modified to flag and skip any data with invalid dates rather than stopping the process and leaving the user without any alternative. Not all users will have capacity to query the database and isolate such entries. That's the case with Seychelles. Uganda will be upgrading their version soon and likely encounter the same problem. 

The upload code used in the old forms was checking the validity of the date for any entry before uploading. I am not sure why that code was not re-used or modified instead of writing another one anew thereby resulting to these issues.

I agree with @mhabimana and @volloholic that a permanent solution is necessary but addressing issues raised by the current users takes the highest priority. However, I don't think reverting to a code that was working well is cosmetic. It can as well be a permanent solution.

**Comment by volloholic** [comment] 2018-12-01 16:48
@smachua Thank you for clarifying I had not seen the mention of the issue for the Seychelles but from your message I understand this is because they also are trying to upload data with incorrect dates.

In practice your suggestion of skipping the upload of such values is easy to implement and @Patowhiz has indicated that he can work on that. This is still not ideal as whenever it happens it is probably a sign that the data may need looking at more closely but that functionality could be added later.

**Comment by Patowhiz** [comment] 2018-12-01 16:49
@smachua I'll do PR that addresses the above issue by Sunday. It will solve
all the 3 problems outlined. We've identified the key areas to look at.

**Closed** 2018-12-04 07:42 UTC
Labels: bug
