### ISSUE TITLE
QC issues

### ISSUE THREAD

**Issue by Iyakaremyevedaste** [opencdms/Climsoft#427] opened 2018-11-23 09:12 UTC
Dear all, there is another issue to solve on QC. When you have say for example data from Jan to October 2018 in obsinitial and it happens previously you did QC for Jan data only. When you want to perform Qc on the remaining months and in your query you select from Jan to Dec. Qc command will be executed but Qc status will not change i.e data cannot be loaded to the obsfinal.

**Comment by mhabimana** [comment] 2018-11-23 09:17
https://github.com/opencdms/Climsoft/issues/420#issuecomment-441078022

**Comment by smachua** [comment] 2018-11-26 09:22
@Iyakaremyevedaste and @mhabimana I am investigating on this issue to find out whether the problem is on QC or the upload operation.

**Comment by Patowhiz** [comment] 2018-11-26 09:36
We will also keep this (QC issues) in mind when we are looking into changes to the upload function as mentioned in issue #420 and #426

**Comment by smachua** [comment] 2018-11-26 21:19
@Iyakaremyevedaste I have tested the QC operation exactly as you described and found it working ok. Please confirm your selections on date range, stations and elements to be sure that you're comparing it correctly. You may send us screen shots if you think you did everything right so that I can do further investigations.

**Comment by Iyakaremyevedaste** [comment] 2018-11-27 12:31
@smachua  I am not in Kigali, I will check & get back to you. I am at ICPAC, are U around so that we meet and discuss further ?

**Comment by mhabimana** [comment] 2018-12-04 12:08
@smachua If the PR to fix the bug in QC is ready,please let me know so that this can be tested and merged.

**Comment by smachua** [comment] 2018-12-07 13:43
Resolved in #429

**Closed** 2019-02-06 08:50 UTC
Labels: bug
