### ISSUE TITLE
4.1 release

### ISSUE THREAD

**Issue by isedwards** [opencdms/Climsoft#321] opened 2018-08-17 10:26 UTC
We currently don't have an estimate for the time it will take to review, test and merge the new functionality in #302 before it goes out for formal testing.

We have the option to delay 4.1 until this is added and tested, or release 4.1 and add this to 4.2 (for release before the end of the year).

This kind of situation is very common in all software projects and it would be normal to not shake things up this close to the current release date, but I see that the new capabilities are important and required, so it is also reasonable to delay the release and get this right.

**Comment by Steve-Palmer** [comment] 2018-08-17 11:03
I suggest we park the double-key-entry work unitl after the testing in Western Kenya, then installation and production testing in Rwanda. We are almost ready to go with the logistics for these activities, so time is tight and a delay of more than a week runs the risk of severely damaging the reputation of the project. In particular, we are gearing up to spend on up to four installation and training visits to different NMHSs between now and the end of March. From April 2019 onwards, the money available from the Met Office VCP will reduce. The hope is that once those visits have been successful (which relies on the R-INSTAT based products and services) other sources of funding will come forward. If we delay, there is a significant risk that we are not able to do more than one or two of the visits before the money ends in March, and that is not enough proof for other funders to commit.

Double-key-entry has been on our wish-list for a very long time. However, trhere is a lot of work to implement it correctly, so to rush and put out a faulty version now would be worse than not including it.

I am very keen that we train managers and users in the user community to expect and implement new releases soon after they are published, and that we publish full releases at fairly short intervals. It has taken a long time to get from 4.0 to 4.1 - I think we should designate the version we are ready to test as 4.1.1 and theree will probably be some bug-fixes which would be 4.1.2 Then we can do the double-key-entry as 4.1.3

**Comment by mhabimana** [comment] 2018-08-17 11:49
@Steve-Palmer: Thanks,at least you are helping us to move forward. I am happy with the idea.

**Comment by smachua** [comment] 2018-08-17 11:51
I strongly support that the planned installation and Instat training in Rwanda go as scheduled in September. It's very important that R-Instat is introduced without any further delay. We found that R-Instat can work with any Climsoft 4.x version. Therefore I can assure all that we're ready for Rwanda installation.
I and Marcellin have successfully tested the double key entry in both New and Old forms. It's already operational in KMD since that is their most trusted QC method. The only thing that is now standing on our way to compiling the final merged code are the current conflicts. Am sure they will be resolved soon.
I therefore suggest that we compile a version 4.1 on what is working then compile version 4.1.2 after the AMI team has completed testing in Western Kenya and any identified issues resolved.

**Comment by isedwards** [comment] 2018-08-17 11:51
Given that double key entry is an important feature, a fortunate consequence of delaying this to the next [minor release](https://semver.org) is that managers will be keen to update to the software to the latest version.

**Comment by mhabimana** [comment] 2018-08-17 13:30
@isedwards @smachua We need to agree on the packaging (contents) of version V4.1 to be released for the testing in Western Kenya and to install in Rwanda.
Just to mention  issues which need to be revised on the  recreated New Data Entry forms by the AMI team:
1.The new recreated data entry forms are not loading missing value (M) into the observation initial, during the uploading time( Note that this should be loaded into the observationinitial table with other values but the M are not sailing through into the observationfinal table) on all the new data entry forms ;
2. Deleting rainfall record on the Form Daily2: This cannot be deleted unless the required total value is provided in the total required text box;
3. The following flags are not required in the form synoptic_2_ra1 since they are playing any role: Flag 178, Flag 179, Flag 180 and hence need to be removed from both the database schema and Entity Framework (EF);
4. Form hourlywind: Displays a bug when there is a case of missing value (M) in the form; this bug need a fix;
5. Observation Hours (HH) on Data entry Forms should be set from Hour 00 to Hour 23 instead of Hour 1 to Hour 24 (currently).

**Comment by smachua** [comment] 2018-08-17 15:51
@mhabimana note that issues 3, 4,5 had been solved in the commit #302 . If it is merged then it's only 1 and 2 that will be pending.

**Comment by mhabimana** [comment] 2018-08-17 16:25
@smachua :Thanks and noted

**Comment by rdstern** [comment] 2018-08-21 16:15
I am confused.  Four days ago there were problems for Ian to merge, (despite being away for family reasons) because 156 files were changed from the master and there were 25 conflicts.  I understood there was then a proposition from Steve (above) to leave the new changes for a quick minor upgrade later.  That would delay the introduction of the double entry until after Rwanda for a minor upgrade.

Now I see the last pull request has 172 files changed and still 16 conflicts.  And the conflicts are mainly on the data entry forms and user controls.  So resolving them might take some time.  I assume also that this means that Marcellin and Samuel would still like double entry to be introduced now?  So there are real differences to resolve.

I suggest either:

a) We take the master as it is now (i.e. without incorporating the latest pull request) and continue with  testing next week, at least in Western Kenya.  Perhaps also with other testers, e.g. Burina Faso. 
b) We wait until early September, when Ian is back, for him with Marcellin and Samuel to look in detail at these changes and move forward more slowly.

If you agree that these are the only alternatives, then I hope a decision could be made quickly.

**Comment by smachua** [comment] 2018-08-21 21:38
@rdstern I don't think there is any confusion. We are always updating the code for things to work better.  The additional changes you're seeing have nothing to do with the implementation of double key entry. After some discussion with @mhabimana we found it necessary to have metadata being updated through gridview hence the additional changes. The only different thing this time is that there are conflicts and the merging didn't succeed.
I do agree that the conflicts were caused by the few updates made in the new key entry forms. But 16 conflicts are few and can be easily resolved. It's unfortunate that Ian is not available for us to look at them together. The sooner this done the better. There are other important changes in that PR.

However I agree with you that:
-Western Kenya testing can start even without merging the recent changes. The new key entry forms were the target of testing.

**Closed** 2019-03-20 18:00 UTC
